 name: Observatório Oceanográfico
email: observatoriooceanografico@gmail.com
description: >-
  Laboratório institucional vinculado à Universidade Federal Fluminense.
url: "https://observatorio-oceanografico.github.io"
baseurl: ""
repository: observatorio-oceanografico/observatorio-oceanografico.github.io

theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

logo: "/assets/img/O2_logo_branco.png"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

  - scope:
      path: "_pages"
    values:
      layout: single
      author_profile: false

  - scope:
      path: "_equipe"
    values:
      layout: academic_profile      

  - scope:
      path: "_noticias"
      type: noticias
    values:
      layout: single
      author_profile: false

navigation: main

collections:
  ensino:
    output: true
    permalink: /ensino/:path/
  projetos:
    output: true
    permalink: /projetos/:path/
  extensao:
    output: true
    permalink: /extensao/:path/
  equipe:
    output: true
    permalink: /equipe/:path/
  noticias:
    output: true
    permalink: /noticias/:year/:month/:day/:title/

include:
  - _pages
  - _noticias
  - assets/css/custom_equipe.css
  
sass:
  style: compressed

